import React, { Component } from "react";
import Plot from "react-plotly.js";

const graphData = {
  masterGraph: {
    title: "Stromal",
    model: "",
    xAxis: "X-Axis",
    yAxis: "Y-Axis",
    zAxis: "Z-Axis",
  },
};

class MySankeyStromalComponent extends Component {
  render() {
    return (
      <Plot
        data={[
          {
            type: "sankey",
            orientation: "h",
            node: {
              color: [
                "#31a354",
                "#e7ba52",
                "#969696",
                "#d6616b",
                "#e7969c",
                "#9c9ede",
                "#843c39",
                "#393b79",
                "#fd8d3c",
                "#3182bd",
                "#6baed6",
                "#ce6dbd",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
                "#800026",
              ],
              label: [
                "Large_Intestine",
                "Muscle",
                "Trachea",
                "Blood",
                "Bladder",
                "Thymus",
                "Vasculature",
                "Spleen",
                "Pancreas",
                "Lung",
                "Small_Intestine",
                "Skin",
                "dendritic cell, human",
                "vein endothelial cell",
                "fibroblast of lung",
                "fibroblast",
                "mesenchymal stem cell",
                "myofibroblast cell",
                "unassigned",
                "skeletal muscle fiber",
                "plasma cell",
                "vascular associated smooth muscle cell",
                "adventitial cell",
                "intermediate epitheliocyte",
                "macrophage",
                "epithelial cell",
                "slow muscle cell",
                "natural killer cell",
                "medullary thymic epithelial cell",
                "endothelial cell",
                "fast muscle cell",
                "myoblast",
                "tendon cell",
                "capillary endothelial cell",
                "mesenchymal cell",
                "pancreatic stellate cell",
                "B cell",
                "ionocyte",
                "smooth muscle cell",
                "stromal cell",
                "pericyte cell",
                "endothelial cell of lymphatic vessel",
                "erythrocyte",
                "mast cell",
                "multi-potent skeletal muscle stem cell",
              ],
              line: {
                color: "black",
                width: 0.5,
              },
              pad: 15,
              thickness: 20,
            },
            link: {
              source: [
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                3,
                0,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                8,
                11,
                10,
                7,
                5,
                5,
                5,
                5,
                2,
                2,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
              ],
              target: [
                36,
                15,
                23,
                24,
                43,
                31,
                17,
                27,
                20,
                38,
                18,
                21,
                13,
                42,
                39,
                22,
                12,
                14,
                37,
                24,
                40,
                21,
                36,
                33,
                41,
                30,
                24,
                43,
                16,
                44,
                31,
                19,
                26,
                38,
                32,
                18,
                35,
                15,
                39,
                42,
                15,
                24,
                28,
                21,
                29,
                34,
                25,
                42,
                15,
                24,
                40,
                20,
                38,
                18,
              ],
              value: [
                45,
                5056,
                27,
                787,
                17,
                913,
                1177,
                249,
                57,
                414,
                159,
                238,
                82,
                250,
                105,
                460,
                194,
                209,
                17,
                92,
                151,
                214,
                26,
                129,
                11,
                38,
                538,
                19,
                8362,
                2724,
                211,
                22,
                29,
                311,
                551,
                65,
                29,
                29,
                31,
                23,
                628,
                47,
                94,
                288,
                14,
                259,
                36,
                84,
                3026,
                1116,
                272,
                24,
                1365,
                68,
              ],
            },
          },
        ]}
        layout={{
          width: 800,
          height: 800,
          margin: {
            l: 50,
            r: 50,
            b: 80,
            t: 90,
            pad: 4,
          },
          title: graphData.masterGraph.title,
          annotations: [
            {
              text: graphData.masterGraph.model,
              font: {
                size: 14,
                color: "#444444",
              },
              showarrow: false,
              align: "center",
              x: 0.5,
              y: 1.1,
              xref: "paper",
              yref: "paper",
            },
          ],
          scene: {
            xaxis: {
              title: graphData.masterGraph.xAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
            yaxis: {
              title: graphData.masterGraph.yAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
            zaxis: {
              title: graphData.masterGraph.zAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
          },
        }}
      />
    );
  }
}

export default MySankeyStromalComponent;
