import React, { Component } from "react";
import Plot from "react-plotly.js";

const graphData = {
  masterGraph: {
    title: "Immune",
    model: "",
    xAxis: "X-Axis",
    yAxis: "Y-Axis",
    zAxis: "Z-Axis",
  },
};

class MySankeyImmuneComponent extends Component {
  render() {
    return (
      <Plot
        data={[
          {
            type: "sankey",
            orientation: "h",
            node: {
              color: [
                "#6baed6",
                "#31a354",
                "#e7ba52",
                "#969696",
                "#d6616b",
                "#e7969c",
                "#ce6dbd",
                "#9c9ede",
                "#843c39",
                "#393b79",
                "#fd8d3c",
                "#3182bd",
                "#8c6d31",
                "#cedb9c",
                "#7b4173",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
                "#e2191c",
              ],
              label: [
                "Small_Intestine",
                "Large_Intestine",
                "Muscle",
                "Trachea",
                "Blood",
                "Bladder",
                "Skin",
                "Thymus",
                "Vasculature",
                "Spleen",
                "Pancreas",
                "Lung",
                "Lymph_Node",
                "Bone_Marrow",
                "Kidney",
                "dendritic cell, human",
                "CD4-positive, alpha-beta memory T cell",
                "cytotoxic T cell",
                "activated CD8-positive, alpha-beta T cell, human",
                "platelet",
                "T-helper 17 cell",
                "fibroblast",
                "mesenchymal stem cell",
                "group 3 innate lymphoid cell",
                "unassigned",
                "pancreatic ductal cell",
                "CD8-positive, alpha-beta memory T cell",
                "neutrophil",
                "plasma cell",
                "vascular associated smooth muscle cell",
                "naive thymus-derived CD8-positive, alpha-beta T cell",
                "non-classical monocyte",
                "intermediate epitheliocyte",
                "hematopoietic stem cell",
                "macrophage",
                "epithelial cell of alveolus of lung",
                "pro-B cell",
                "CD4-positive helper T cell",
                "club cell",
                "memory B cell",
                "CD8-positive, alpha-beta T cell",
                "intermediate monocyte",
                "natural killer cell",
                "kidney epithelial cell",
                "multi-potent skeletal muscle stem cell",
                "erythroid progenitor cell",
                "medullary thymic epithelial cell",
                "type II pneumocyte",
                "T cell",
                "enterocyte",
                "T follicular helper cell",
                "endothelial cell",
                "follicular B cell",
                "DN1 thymic pro-T cell",
                "fast muscle cell",
                "granulocyte",
                "basophil",
                "endothelial cell of artery",
                "respiratory goblet cell",
                "plasmacytoid dendritic cell",
                "Langerhans cell",
                "plasmacytoid dendritic cell, human",
                "capillary endothelial cell",
                "myeloid cell",
                "pancreatic stellate cell",
                "CD4-positive, alpha-beta T cell",
                "monocyte",
                "B cell",
                "CD34-positive, CD38-negative multipotent progenitor cell",
                "mature NK T cell",
                "naive thymus-derived CD4-positive, alpha-beta T cell",
                "double negative thymocyte",
                "smooth muscle cell",
                "conventional dendritic cell",
                "effector memory CD8-positive, alpha-beta T cell",
                "classical monocyte",
                "megakaryocyte",
                "erythrocyte",
                "mast cell",
                "naive B cell",
                "effector memory CD4-positive, alpha-beta T cell",
                "lung microvascular endothelial cell",
                "memory T cell",
              ],
              line: { color: "black", width: 0.5 },
              pad: 15,
              thickness: 20,
            },
            link: {
              source: [
                5,
                5,
                5,
                5,
                5,
                5,
                5,
                5,
                5,
                5,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                14,
                1,
                1,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                10,
                10,
                10,
                10,
                10,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                0,
                0,
                0,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                3,
                3,
                3,
                8,
                8,
                8,
                8,
                8,
              ],
              target: [
                67,
                48,
                32,
                34,
                78,
                69,
                42,
                28,
                61,
                24,
                67,
                37,
                16,
                26,
                75,
                15,
                74,
                77,
                78,
                76,
                39,
                70,
                30,
                42,
                27,
                31,
                28,
                19,
                68,
                37,
                40,
                45,
                52,
                55,
                33,
                66,
                42,
                27,
                28,
                24,
                67,
                48,
                62,
                51,
                54,
                21,
                43,
                22,
                63,
                79,
                42,
                27,
                24,
                67,
                48,
                67,
                16,
                56,
                75,
                38,
                15,
                80,
                74,
                57,
                35,
                81,
                34,
                30,
                42,
                31,
                28,
                61,
                58,
                47,
                24,
                67,
                50,
                18,
                56,
                75,
                73,
                41,
                78,
                69,
                39,
                79,
                70,
                31,
                28,
                59,
                67,
                40,
                48,
                34,
                78,
                44,
                72,
                24,
                48,
                51,
                34,
                25,
                64,
                60,
                48,
                73,
                17,
                34,
                78,
                82,
                67,
                48,
                49,
                67,
                37,
                50,
                18,
                75,
                73,
                77,
                69,
                39,
                79,
                70,
                42,
                27,
                31,
                28,
                59,
                24,
                65,
                16,
                53,
                50,
                20,
                15,
                71,
                23,
                34,
                69,
                46,
                66,
                79,
                42,
                28,
                36,
                29,
                67,
                48,
                24,
                67,
                48,
                34,
                78,
                28,
              ],
              value: [
                549,
                2366,
                26,
                3743,
                1252,
                518,
                683,
                1147,
                129,
                100,
                675,
                925,
                838,
                697,
                5423,
                560,
                266,
                513,
                103,
                115,
                62,
                695,
                330,
                611,
                1310,
                2143,
                231,
                262,
                370,
                394,
                330,
                43,
                218,
                230,
                166,
                414,
                375,
                305,
                299,
                36,
                554,
                930,
                37,
                27,
                23,
                17,
                57,
                32,
                293,
                18,
                303,
                136,
                332,
                29,
                43,
                277,
                426,
                702,
                790,
                11,
                2133,
                556,
                349,
                13,
                160,
                33,
                10151,
                406,
                289,
                1470,
                133,
                92,
                11,
                554,
                274,
                2414,
                1682,
                838,
                414,
                155,
                93,
                92,
                492,
                124,
                518,
                1846,
                906,
                79,
                307,
                54,
                82,
                503,
                507,
                886,
                28,
                20,
                24,
                11,
                181,
                21,
                148,
                70,
                14,
                39,
                139,
                55,
                47,
                102,
                129,
                78,
                88,
                174,
                22,
                1118,
                371,
                105,
                888,
                942,
                178,
                59,
                584,
                785,
                769,
                394,
                756,
                153,
                516,
                304,
                49,
                206,
                829,
                215,
                59,
                1024,
                593,
                50,
                2112,
                219,
                127,
                514,
                13,
                334,
                2239,
                162,
                108,
                648,
                12,
                22,
                39,
                17,
                13,
                320,
                552,
                63,
                29,
              ],
            },
          },
        ]}
        layout={{
          width: 800,
          height: 900,
          margin: {
            l: 50,
            r: 50,
            b: 80,
            t: 90,
            pad: 4,
          },
          title: graphData.masterGraph.title,
          annotations: [
            {
              text: graphData.masterGraph.model,
              font: {
                size: 14,
                color: "#444444",
              },
              showarrow: false,
              align: "center",
              x: 0.5,
              y: 1.1,
              xref: "paper",
              yref: "paper",
            },
          ],
          scene: {
            xaxis: {
              title: graphData.masterGraph.xAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
            yaxis: {
              title: graphData.masterGraph.yAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
            zaxis: {
              title: graphData.masterGraph.zAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
          },
        }}
      />
    );
  }
}

export default MySankeyImmuneComponent;
