import React, { Component } from "react";
import Plot from "react-plotly.js";

const graphData = {
  masterGraph: {
    title: "Endothelial",
    model: "",
    xAxis: "X-Axis",
    yAxis: "Y-Axis",
    zAxis: "Z-Axis",
  },
};

class MySankeyEndothelialComponent extends Component {
  render() {
    return (
      <Plot
        data={[
          {
            type: "sankey",
            orientation: "h",
            node: {
              color: [
                "#31a354",
                "#e7ba52",
                "#969696",
                "#843c39",
                "#e7969c",
                "#ce6dbd",
                "#9c9ede",
                "#393b79",
                "#fd8d3c",
                "#3182bd",
                "#6baed6",
                "#7b4173",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
                "#fed976",
              ],
              label: [
                "Large_Intestine",
                "Muscle",
                "Trachea",
                "Vasculature",
                "Bladder",
                "Skin",
                "Thymus",
                "Spleen",
                "Pancreas",
                "Lung",
                "Small_Intestine",
                "Kidney",
                "dendritic cell, human",
                "CD4-positive, alpha-beta memory T cell",
                "vein endothelial cell",
                "basal cell",
                "mesenchymal stem cell",
                "group 3 innate lymphoid cell",
                "vascular associated smooth muscle cell",
                "naive thymus-derived CD8-positive, alpha-beta T cell",
                "macrophage",
                "pro-B cell",
                "type I pneumocyte",
                "club cell",
                "natural killer cell",
                "type II pneumocyte",
                "T follicular helper cell",
                "endothelial cell",
                "endothelial cell of artery",
                "plasmacytoid dendritic cell",
                "capillary endothelial cell",
                "lymphocyte",
                "B cell",
                "smooth muscle cell",
                "endothelial cell of vascular tree",
                "pericyte cell",
                "endothelial cell of lymphatic vessel",
                "effector memory CD8-positive, alpha-beta T cell",
                "classical monocyte",
                "lung microvascular endothelial cell",
                "pancreatic stellate cell",
                "multi-potent skeletal muscle stem cell",
              ],
              line: {
                color: "black",
                width: 0.5,
              },
              pad: 15,
              thickness: 20,
            },
            link: {
              source: [
                4,
                4,
                4,
                4,
                4,
                11,
                0,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                8,
                8,
                5,
                10,
                7,
                6,
                6,
                6,
                6,
                6,
                6,
                2,
                3,
                3,
                3,
                3,
                3,
              ],
              target: [
                32,
                27,
                20,
                18,
                14,
                27,
                27,
                13,
                15,
                30,
                38,
                23,
                12,
                37,
                28,
                36,
                39,
                20,
                19,
                24,
                35,
                22,
                25,
                18,
                14,
                32,
                30,
                28,
                36,
                34,
                20,
                16,
                41,
                33,
                27,
                40,
                34,
                27,
                29,
                26,
                27,
                17,
                31,
                21,
                18,
                27,
                27,
                28,
                20,
                35,
                33,
              ],
              value: [
                14,
                191,
                49,
                204,
                269,
                92,
                26,
                18,
                159,
                1954,
                97,
                27,
                109,
                11,
                695,
                74,
                552,
                961,
                111,
                21,
                39,
                28,
                54,
                54,
                445,
                83,
                2286,
                214,
                98,
                2900,
                97,
                29,
                51,
                527,
                270,
                14,
                57,
                34,
                147,
                15,
                1829,
                13,
                188,
                56,
                362,
                37,
                1032,
                274,
                124,
                48,
                56,
              ],
            },
          },
        ]}
        layout={{
          width: 800,
          height: 800,
          margin: {
            l: 50,
            r: 50,
            b: 80,
            t: 90,
            pad: 4,
          },
          title: graphData.masterGraph.title,
          annotations: [
            {
              text: graphData.masterGraph.model,
              font: {
                size: 14,
                color: "#444444",
              },
              showarrow: false,
              align: "center",
              x: 0.5,
              y: 1.1,
              xref: "paper",
              yref: "paper",
            },
          ],
          scene: {
            xaxis: {
              title: graphData.masterGraph.xAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
            yaxis: {
              title: graphData.masterGraph.yAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
            zaxis: {
              title: graphData.masterGraph.zAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
          },
        }}
      />
    );
  }
}

export default MySankeyEndothelialComponent;
