version: '3'

services:
  backend:
    container_name: backend
    build: ./test_backend
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./test_backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - API_HOST="http://localhost:3000/"
      - API_SERVER_PORT=5000
    depends_on:
      - frontend

  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      - REACT_APP_PORT=3000
    expose:
      - 3000 
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/usr/src/app/src


