import React, { Component } from "react";
import Plot from "react-plotly.js";
import Grid from "@material-ui/core/Grid";

const graphData = {
  masterGraph: {
    title: "Title",
    model: "",
    xAxis: "X-Axis",
    yAxis: "Y-Axis",
    zAxis: "Z-Axis",
  },
};

class MySankeyComponent extends Component {
  render() {
    return (
      <div id="all-sankeys">
        <Grid container spacing={3}>
          <Grid item xs={6}>
            <BulletTreeStory />
          </Grid>
          <Grid item xs={6}>
            <img
              src="../../images/CLIAHUBworkflow.png"
              alt="LIMS"
              width="100%"
            />
          </Grid>
        </Grid>
        <div id="epithelial">
          <Plot
            data={[
              {
                type: "sankey",
                orientation: "h",
                node: {
                  color: [
                    "#31a354",
                    "#e7ba52",
                    "#969696",
                    "#843c39",
                    "#e7969c",
                    "#ce6dbd",
                    "#9c9ede",
                    "#fd8d3c",
                    "#3182bd",
                    "#6baed6",
                    "#7b4173",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                    "#fd8c3c",
                  ],
                  label: [
                    "Large_Intestine",
                    "Muscle",
                    "Trachea",
                    "Vasculature",
                    "Bladder",
                    "Skin",
                    "Thymus",
                    "Pancreas",
                    "Lung",
                    "Small_Intestine",
                    "Kidney",
                    "basal cell",
                    "fibroblast",
                    "mesenchymal stem cell",
                    "large intestine crypt goblet cell",
                    "unassigned",
                    "pancreatic ductal cell",
                    "skeletal muscle fiber",
                    "ciliated cell",
                    "neutrophil",
                    "bladder urothelial cell",
                    "pancreatic acinar cell",
                    "vascular associated smooth muscle cell",
                    "adventitial cell",
                    "naive thymus-derived CD8-positive, alpha-beta T cell",
                    "intermediate epitheliocyte",
                    "epithelial cell of alveolus of lung",
                    "intestinal crypt stem cell",
                    "macrophage",
                    "type I pneumocyte",
                    "epithelial cell",
                    "club cell",
                    "natural killer cell",
                    "kidney epithelial cell",
                    "medullary thymic epithelial cell",
                    "paneth cell",
                    "type II pneumocyte",
                    "T cell",
                    "type B pancreatic cell",
                    "enterocyte",
                    "secretory cell",
                    "endothelial cell",
                    "goblet cell",
                    "fast muscle cell",
                    "tendon cell",
                    "enterocyte of epithelium of small intestine",
                    "basophil",
                    "respiratory goblet cell",
                    "capillary endothelial cell",
                    "B cell",
                    "ionocyte",
                    "pancreatic A cell",
                    "smooth muscle cell",
                    "stromal cell",
                    "endothelial cell of lymphatic vessel",
                    "effector memory CD8-positive, alpha-beta T cell",
                    "lung ciliated cell",
                    "naive B cell",
                    "multi-potent skeletal muscle stem cell",
                    "enteroendocrine cell",
                    "memory T cell",
                  ],
                  line: { color: "black", width: 0.5 },
                  pad: 15,
                  thickness: 20,
                },
                link: {
                  source: [
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    10,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    1,
                    1,
                    1,
                    1,
                    1,
                    7,
                    7,
                    7,
                    7,
                    7,
                    5,
                    5,
                    5,
                    5,
                    9,
                    9,
                    9,
                    9,
                    9,
                    9,
                    9,
                    9,
                    6,
                    2,
                    2,
                    2,
                    2,
                    2,
                    2,
                    2,
                    2,
                    2,
                    3,
                  ],
                  target: [
                    49,
                    11,
                    20,
                    25,
                    32,
                    15,
                    22,
                    49,
                    37,
                    48,
                    41,
                    43,
                    12,
                    33,
                    13,
                    57,
                    32,
                    19,
                    15,
                    49,
                    37,
                    41,
                    39,
                    59,
                    42,
                    27,
                    14,
                    23,
                    11,
                    46,
                    31,
                    55,
                    26,
                    50,
                    56,
                    28,
                    24,
                    47,
                    29,
                    36,
                    15,
                    54,
                    58,
                    17,
                    52,
                    44,
                    37,
                    51,
                    21,
                    16,
                    38,
                    37,
                    30,
                    28,
                    60,
                    37,
                    39,
                    45,
                    59,
                    42,
                    27,
                    35,
                    53,
                    34,
                    49,
                    37,
                    11,
                    46,
                    18,
                    41,
                    25,
                    40,
                    15,
                    30,
                  ],
                  value: [
                    32,
                    676,
                    1548,
                    784,
                    808,
                    1099,
                    260,
                    129,
                    71,
                    968,
                    669,
                    852,
                    888,
                    14089,
                    669,
                    167,
                    244,
                    16,
                    2615,
                    16,
                    16,
                    20,
                    2541,
                    1179,
                    1850,
                    1104,
                    1241,
                    46,
                    2038,
                    23,
                    1205,
                    81,
                    230,
                    38,
                    646,
                    170,
                    25,
                    964,
                    332,
                    5595,
                    32,
                    11,
                    94,
                    20,
                    163,
                    13,
                    14,
                    227,
                    5888,
                    1887,
                    84,
                    13,
                    73,
                    12,
                    27,
                    31,
                    6221,
                    1507,
                    119,
                    313,
                    525,
                    409,
                    45,
                    47,
                    276,
                    181,
                    2709,
                    31,
                    366,
                    30,
                    1173,
                    1956,
                    903,
                    28,
                  ],
                },
              },
            ]}
            layout={{
              width: 800,
              height: 600,
              margin: {
                l: 50,
                r: 50,
                b: 80,
                t: 90,
                pad: 4,
              },
              title: "Epithelial",
              annotations: [
                {
                  text: graphData.masterGraph.model,
                  font: {
                    size: 14,
                    color: "#444444",
                  },
                  showarrow: false,
                  align: "center",
                  x: 0.5,
                  y: 1.1,
                  xref: "paper",
                  yref: "paper",
                },
              ],
              scene: {
                xaxis: {
                  title: graphData.masterGraph.xAxis,
                  titlefont: {
                    family: "Courier New, monospace",
                    size: 12,
                    color: "#444444",
                  },
                },
                yaxis: {
                  title: graphData.masterGraph.yAxis,
                  titlefont: {
                    family: "Courier New, monospace",
                    size: 12,
                    color: "#444444",
                  },
                },
                zaxis: {
                  title: graphData.masterGraph.zAxis,
                  titlefont: {
                    family: "Courier New, monospace",
                    size: 12,
                    color: "#444444",
                  },
                },
              },
            }}
          />
        </div>
      </div>
    );
  }
}

export default MySankeyComponent;
