name: tabula_sapiens
channels:
    - conda-forge
    - bioconda
    - r

dependencies:
    - absl-py==0.9.0
    - anndata==0.7.4
    - asn1crypto==1.0.1
    - astor==0.8.1
    - backcall==0.1.0
    - certifi==2019.9.11
    - cffi==1.12.3
    - chardet==3.0.4
    - cryptography==2.7
    - cycler==0.10.0
    - dataclasses==0.7
    - decorator==4.4.1
    - fbpca==1.0
    - flask==1.1.2
    - gast==0.3.2
    - h5py==2.9.0
    - idna==2.8
    - intervaltree==2.1.0
    - ipython==7.11.1
    - ipywidgets
    - ipykernel
    - jedi==0.15.2
    - joblib==0.14.1
    - jupyterlab==2.2.4
    - Keras-Applications==1.0.8
    - Keras-Preprocessing==1.1.0
    - kiwisolver==1.1.0
    - legacy-api-wrap==1.2
    - leidenalg==0.7.0
    - louvain==0.6.1
    - Markdown==3.1.1
    - matplotlib==3.0.3
    - mock==3.0.5
    - more-itertools==8.1.0
    - natsort==7.0.0
    - networkx==2.4
    - numba==0.47.0
    - numexpr==2.7.1
    - numpy==1.18.1
    - packaging==20.0
    - pandas==1.1.0
    - parso==0.5.2
    - patsy==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pip==20.2.1
    - protobuf==3.11.2
    - ptyprocess==0.6.0
    - pycosat==0.6.3
    - pycparser==2.19
    - Pygments==2.5.2
    - pyOpenSSL==19.0.0
    - pyparsing==2.4.6
    - PySocks==1.7.1
    - python-dateutil==2.8.1
    - python-igraph==0.7.1.post6
    - pytz==2019.3
    - requests==2.22.0
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - scvi>=0.6.5
    - seaborn==0.9.0
    - six==1.12.0
    - sortedcontainers==2.1.0
    - tensorboard==1.13.1
    - tensorflow==1.13.1
    - tensorflow-estimator==1.13.0
    - termcolor==1.1.0
    - tqdm==4.36.1
    - traitlets==4.3.3
    - umap-learn==0.3.10
    - urllib3==1.24.2
    - wcwidth==0.1.8
    - Werkzeug==0.16.0
    - zipp==1.0.0
    - pip:
        - annoy==1.16.3
        - bbknn==1.3.12
        - scanorama==1.4
        - grpcio==1.26.0
        - onclass==0.93
        - setuptools-scm==3.3.3
        - prompt-toolkit==3.0.2
        - ruamel-yaml==0.15.46
        - statsmodels==0.11.0rc2
        - scanpy==1.6.0
        - scikit-misc==0.1.3
        - get-version==2.1
        - ipython-genutils==0.2.0
        - rpy2==3.3.5
        - importlib-metadata==1.4.0
        - tables==3.6.1
