__default__:
    time: '8:00:00'
    name: "{rule}"
    partition: normal,owners,quake
    mem: '8000'
    ntasks: '1'
    cpus-per-task: '2'
    output: 'snakemake_logs/slurm_logs/{rule}_%j.out'
    error: 'snakemake_logs/slurm_logs/{rule}_%j.err'
cellranger_vdj:
    time: '10:00:00'
    name: '{rule}'
    partition: owners,quake
    mem: '210000'
    ntasks: '1'
    cpus-per-task: '20'
    output: 'snakemake_logs/slurm_logs/{rule}_%j.out'
    error: 'snakemake_logs/slurm_logs/{rule}_%j.err'
